---                              
- name: user create              
  hosts: all                     
  tasks:                         
    - include_vars: https://github.com/linuxsrilanka/tower/blob/main/key-based-userlist.yml
      tags:                      
        - move_home              
        - renew_keys             
        - defpermit              
                                                                       
    - name: Add user group       
      group:                     
        name: "{{ item.name}}"   
        gid:  "{{item.gid}}"     
        state: present           
                                                                                                                                          
    - name: user add             
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        group: "{{item.name}}"
        password: "{{item.pass}}"
        update_password: always
        comment: "{{item.comment}}"
      loop: "{{users}}"
    
    - name: copy password file
      copy:
       src: /etc/passwd
       dest: /home/chroot/etc/passwd
       remote_src: yes
    
    - name: move home dirs
      shell:
       cmd: '[ -d /home/chroot/home/{{item.name}}] && echo || mv /home/{{item.name}} /home/chroot/home/'
      loop: "{{users}}"
      tags:
        - move_home
    - name: create .ssh dir
      file: 
        path: "/home/chroot/home/{{item.name}}/.ssh"
        state: "{{diretory}}"
        owner: "{{iteam.name}}"
        group: "{{item.name}}"
        mode: 0700
      loop: "{{users}}"

    - name: Configue ssh keys
      authorized_key:
        user: "{{item.name}}"
        key: "{{lookup ('file','./pub-key/{{item.name}}') }}"
        path:  "/home/chroot/home/{{item.name}}/.ssh/authorized_keys"
     
    - name: Create user permit config files and default line
      shell:
        cmd: '[ -f ./user-permit-config/{{item.name}} ] && echo || echo 1.1.1.1:1 > ./user-permit-config/{{item.name}}' 
      loop: "{{ users }}"
      become_user: jumpadmin
      delegate_to: localhost
      tags:
      - defpermit
