---
- name: Create User
  hosts: all
  tasks:
  tags:
    - move_home
    - renew_keys
    - defpermit
    
    - name: Add user Group
      group:
        name: "{{ name }}"
        gid: "{{ gid }}"
        state: present
   
    
    - name: Add User
      user:
        name: "{{ name }}"
        uid: "{{ uid }}"
        group: "{{ name }}"
        state: present
        password: "{{ pass }}"
        update_password: always
        comment: "{{ comment }}"
     
    
    - name: Copy password file
      copy:
        src: /etc/passwd
        dest: /home/chroot/etc/passwd
        remote_src: yes
   
    - name: move home dirs
      shell:
        cmd: '[ -d /home/chroot/home/{{name}} ] && echo ||  mv /home/{{name}} /home/chroot/home/'
      tags:
        - move_home

    
    - name: create .ssh dir
      file:
        path: "/home/chroot/home/{{name}}/.ssh"
        state: directory
        owner: "{{ name }}"
        group: "{{ name }}"
        mode: 0700

   
    - name: Configure ssh keys
      authorized_key:
        user: "{{ name }}"
        key: "{{ lookup ('file', '/var/lib/awx/venv/ansible/pub-keys/{{name}}') }}"
        path: "/home/chroot/home/{{name}}/.ssh/authorized_keys"
        state: present
      tags: renew_keys

   
    - name: Create user permit config files and default line
      shell:
        cmd: '[ -f ./user-permit-config/{{name}} ] && echo || echo 1.1.1.1:1 > ./user-permit-config/{{name}}'

      become_user: jumpadmin
      delegate_to: localhost
      tags:
      - defpermit
