---                              
- name: user create              
  hosts: all                     
  tasks:                         
    tags:                      
      - move_home              
      - renew_keys             
      - defpermit              
                                                                       
    - name: Add user group       
      group:                     
        name: "{{name}}"   
        gid:  "{{gid}}"     
        state: present          
                                                                                                                                          
    - name: user add             
      user:
        name: "{{name}}"
        uid: "{{uid}}"
        group: "{{name}}"
        password: "{{pass}}"
        update_password: always
        comment: "{{item.comment}}"
    
    - name: copy password file
      copy:
       src: /etc/passwd
       dest: /home/chroot/etc/passwd
       remote_src: yes
    
    - name: move home dirs
      shell:
       cmd: '[ -d /home/chroot/home/{{item.name}}] && echo || mv /home/{{item.name}} /home/chroot/home/'
      loop: "{{users}}"
      tags:
        - move_home

    - name: "create .ssh dir"
      file: 
        path: "/home/chroot/home/{{item.name}}/.ssh"
        state: directory
        owner: "{{item.name}}"
        group: "{{item.name}}"
        mode: 0700
      loop: "{{users}}"

    - name: Configue ssh keys
      authorized_key:
        user: "{{item.name}}"
        key: "{{lookup ('file', './pub-keys/{{item.name}}') }}"
        path:  "/home/chroot/home/{{item.name}}/.ssh/authorized_keys"
      loop: "{{ users }}"
